Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-24.04"
  config.vm.provider "vmware_desktop" do |v|
    v.gui = false
    v.vmx["memsize"] = "1024"
    v.vmx["numvcpus"] = "2"
  end
  config.vm.define :vm1 do |vm1|
    config.vm.hostname = "uba"
    vm1.vm.network "private_network", ip: "192.168.56.2"
    vm1.vm.provision "shell", path: "./scripts/install_Ansible.sh"
  end
  config.vm.define :vm2 do |vm2|
    config.vm.hostname = "uba"
    vm2.vm.network "private_network", ip: "192.168.56.3"
    vm2.vm.provision "shell", path: "./scripts/install_Ansible.sh"
  end
  config.vm.define :vm3 do |vm3|
    config.vm.hostname = "uba"
    vm3.vm.network "private_network", ip: "192.168.56.4"
    vm3.vm.provision "shell", path: "./scripts/install_Ansible.sh"
  end
end