- name: Deploy wordpress
  hosts: myhosts
  remote_user: ubuntu
  tasks:
    - name: Clone the repository of source files
      ansible.builtin.git:
        repo: "https://github.com/UBA-code/cloud-1-blog.git"
        dest: $HOME/site
        force: true

    - name: Copy the .env into wordpress directory
      ansible.builtin.copy:
        src: ../secrets/.env
        dest: $HOME/site

    - name: build and run the containers
      ansible.builtin.command:
        cmd: docker compose up --build -d
        chdir: /home/ubuntu/site
      become: yes

    - name: Ensure a duckdns update ip curl request is added to .bachrc
      ansible.builtin.lineinfile:
        path: "$HOME/.bashrc"
        line: 'curl "https://www.duckdns.org/update?domains=cloud-2&token=a4a8a73c-9a63-4a9a-8646-4f19a6d54270&ip=&verbose=true"'
        state: present
        create: yes
        mode: "0644"

    - name: Make a curl request to duckdns to change ip of domain 'cloud-1' into the machine ip
      ansible.builtin.command: curl "https://www.duckdns.org/update?domains=cloud-2&token=a4a8a73c-9a63-4a9a-8646-4f19a6d54270&ip=&verbose=true"
      register: duckdns_response

    - name: Print the duckdns reponse
      ansible.builtin.debug:
        msg: "{{ duckdns_response.stdout }}"

    - name: Generate let's encrypt certificates
      ansible.builtin.command:
        cmd: docker compose run --rm certbot certonly --webroot --webroot-path=/var/www/certbot --email ymks9330@gmail.com --agree-tos --no-eff-email -d cloud-2.duckdns.org --non-interactive
        chdir: /home/ubuntu/site
      register: certbot_output
      become: yes

    - name: Print certbot container output
      ansible.builtin.debug:
        msg: "{{ certbot_output.stdout }}"

    - name: Change the nginx config file to final one that contain ssl
      ansible.builtin.shell:
        cmd: "mv nginx.conf nginx.conf.initial && mv nginx.conf.final nginx.conf"
        chdir: $HOME/site/nginx-conf/

    - name: Restart nginx
      ansible.builtin.command:
        cmd: docker compose exec nginx nginx -s reload
        chdir: /home/ubuntu/site
      become: yes

    - name: Copy renew script to the server
      ansible.builtin.copy:
        src: "../scripts/renew_certificate.sh"
        dest: "/home/ubuntu/"
        mode: 744

    - name: Add certbot renew task to anacron for auto renew every month
      ansible.builtin.lineinfile:
        path: /etc/anacrontab
        line: "7  1 cron.renew_task /home/ubuntu/renew_certificate.sh"
        state: present
      become: true

    - name: Run anacron to check if some tasks didn't run
      ansible.builtin.command: anacron
      become: true
