- name: Deploy wordpress
  hosts: myhosts
  remote_user: root
  tasks:
    - name: Clone the repository of source files
      ansible.builtin.git:
        repo: 'https://github.com/UBA-code/cloud-1-blog.git'
        dest: $HOME/site
    - name: Copy the .env into wordpress directory
      ansible.builtin.copy:
        src: ../secrets/.env
        dest: $HOME/site
    - name: build and run the containers
      ansible.builtin.command: chdir=$HOME/site/ docker compose up --build -d
      register: docker_result
    - name: Display the output
      debug:
        msg: "{{ docker_result.stdout }}"